### ISSUE TITLE
empty zTXT chunk gives error

### ISSUE THREAD

**Issue by leonbloy** [jsummers/tweakpng#4]
I created an empty zTXT with empty val (kinda stupid, but valid thing), and tweakPNG  gives an inflate error when reading it. I'm not 100% sure that this is bug in TweakPNG but I believe my  deflated data is ok (in hexa: 78 9C 03 00 00 00 00 01), and ImageMagick seems to read it ok. I can send you my test image

**Comment by TomasHubelbauer** [comment]
I am dealing with the same issue right now, but in my case I initially wanted to create the empty chunk intentionally. I was using TweakPNG to validate a JavaScript program that I wrote that inserts `tEXt` chunks into a PNG in the browser and I figured I best start with an empty chunk so that I don't have to deal with the CRC yet - it will be zero. Then I realized I still need to do CRC from the get-go because the chunk type bytes are a part of the CRC'd slice so that's where that ended, **but:**

As I was trying to do that, I attempted to add an empty `tEXt` chunk to an existing image by opening it, going to Insert > tEXt > clearing the Keyword field and focusing the value field (so that upon clicking OK the keyword field doesn't reset back to default - `Comment`) and when I click OK then, the program freezes and then crashes.

So this issue still seems to be there.
